const fruits = [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bilberry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Currant",
  "Cherry",
  "Cherimoya",
  "Clementine",
  "Date",
  "Damson",
  "Durian",
  "Eggplant",
  "Elderberry",
  "Feijoa",
  "Gooseberry",
  "Grape",
  "Grapefruit",
  "Guava",
  "Huckleberry",
  "Jackfruit",
  "Jambul",
  "Kiwi fruit",
  "Kumquat",
  "Legume",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Mangostine",
  "Melon",
  "Cantaloupe",
  "Honeydew melon",
  "Watermelon",
  "Rock melon",
  "Nectarine",
  "Orange",
  "Peach",
  "Pear",
  "Williams pear or Bartlett pear",
  "Pitaya",
  "Physalis",
  "Plum/prune (dried plum)",
  "Pineapple",
  "Pomegranate",
  "Raisin",
  "Raspberry",
  "Western raspberry (blackcap)",
  "Rambutan",
  "Redcurrant",
  "Salal berry",
  "Satsuma",
  "Star fruit",
  "Strawberry",
  "Tangerine",
  "Tomato",
  "Ugli fruit",
  "Watermelon",
  "Ziziphus mauritiana"
]

export default fruits