export const fruits = [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bartlett pear",
  "Bilberry",
  "Blackberry",
  "Blackcap",
  "Blackcurrant",
  "Blueberry",
  "Cantaloupe",
  "Cherry",
  "Cherimoya",
  "Clementine",
  "Currant",
  "Date",
  "Damson",
  "Durian",
  "Eggplant",
  "Elderberry",
  "Feijoa",
  "Gooseberry",
  "Grape",
  "Grapefruit",
  "Guava",
  "Honeydew melon",
  "Huckleberry",
  "Jackfruit",
  "Jambul",
  "Kiwi fruit",
  "Kumquat",
  "Legume",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Mangostine",
  "Melon",
  "Rock melon",
  "Nectarine",
  "Orange",
  "Peach",
  "Pear",
  "Physalis",
  "Pineapple",
  "Pitaya",
  "Plum",
  "Pomegranate",
  "Prune",
  "Raisin",
  "Raspberry",
  "Rambutan",
  "Redcurrant",
  "Salal berry",
  "Satsuma",
  "Star fruit",
  "Strawberry",
  "Tangerine",
  "Tomato",
  "Ugli fruit",
  "Watermelon",
  "Western raspberry",
  "Williams pear",
  "Ziziphus mauritiana"
]

export const vegetables = [
  "Acorn Squash",
  "Alfalfa Sprouts",
  "Artichoke",
  "Arugula",
  "Asparagus",
  "Aubergine",
  "Azuki Beans",
  "Banana Squash",
  "Bean Sprouts",
  "Beet Greens",
  "Beetroot",
  "Bell Pepper",
  "Bitter Melon",
  "Black-Eyed Peas",
  "Black Beans",
  "Bok Choy",
  "Borlotti Bean",
  "Broad Beans",
  "Broccoflower (A Hybrid)",
  "Broccoli (Calabrese)",
  "Brussels Sprouts",
  "Butter Bean",
  "Butternut Squash",
  "Cabbage",
  "Carrot",
  "Cauliflower",
  "Ceci Beans",
  "Celeriac",
  "Celery",
  "Chard",
  "Chickpeas",
  "Chili Pepper",
  "Chives",
  "Collard Greens",
  "Corms",
  "Courgette",
  "Cucumber",
  "Daikon Or White Radish",
  "Delicata",
  "Eddoe",
  "Eggplant",
  "Endive",
  "Fennel",
  "Fiddleheads",
  "Frisee",
  "Garbanzos",
  "Garlic",
  "Gem Squash",
  "Ginger",
  "Green Beans",
  "Green Onion",
  "Greens",
  "Habanero",
  "Horseradish",
  "Hubbard Squash",
  "Jalapeño",
  "Jerusalem Artichoke",
  "Jicama",
  "Kale",
  "Kidney Beans",
  "Kohlrabi",
  "Konjac",
  "Leek",
  "Legumes",
  "Lentils",
  "Lettuce",
  "Lima Beans",
  "Mangel-Wurzel",
  "Mange Tout",
  "Marrow",
  "Mung Beans",
  "Mustard Greens",
  "Navy Beans",
  "Nettles",
  "New Zealand Spinach",
  "Okra",
  "Onion",
  "Onions",
  "Oyster Plant",
  "Parsnip",
  "Peanuts",
  "Peas",
  "Peppers",
  "Pinto Beans",
  "Potato",
  "Radicchio",
  "Radish",
  "Red Cabbage",
  "Rhubarb",
  "Rocket",
  "Runner Beans",
  "Rutabaga",
  "Salsify",
  "Savoy Cabbage",
  "Scallion",
  "Shallot",
  "Skirret",
  "Snap Peas",
  "Soy Beans",
  "Spaghetti Squash",
  "Spinach",
  "Split Peas",
  "Spring Onion",
  "Squash",
  "Sweetcorn",
  "Sweet Potato",
  "Taro",
  "Tat Soi",
  "Tomato",
  "Topinambur",
  "Tubers",
  "Turnip",
  "Wasabi",
  "Water Chestnut",
  "Watercress",
  "Yam",
  "Zucchini"
]

export const books = [
  { title: 'Last Argument of Kings', author: 'Joe Abercrombie' },
  { title: 'Legend', author: 'Marie Lu' },
  { title: 'Life After Life', author: 'Kate Atkinson' },
  { title: 'Like Water for Chocolate', author: 'Laura Esquivel' },
  { title: 'Little House on the Prairie', author: 'Laura Ingalls Wilder' },
  { title: 'Little Women', author: 'Louisa May Alcott' },
  { title: 'Long Day\'s Journey into Night', author: 'Eugene O\'Neill' },
  { title: 'Lord Jim', author: 'Joseph Conrad' },
  { title: 'Lord of the Flies', author: 'William Golding' },
  { title: 'Lord of the Rings', author: 'J. R. R. Tolkien' }
]