const fruits = [
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bilberry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Cantaloupe",
  "Cherry",
  "Cherimoya",
  "Clementine",
  "Currant",
  "Date",
  "Damson",
  "Durian",
  "Eggplant",
  "Elderberry",
  "Feijoa",
  "Gooseberry",
  "Grape",
  "Grapefruit",
  "Guava",
  "Honeydew melon",
  "Huckleberry",
  "Jackfruit",
  "Jambul",
  "Kiwi fruit",
  "Kumquat",
  "Legume",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Mangostine",
  "Melon",
  "Rock melon",
  "Nectarine",
  "Orange",
  "Peach",
  "Pear",
  "Physalis",
  "Pineapple",
  "Pitaya",
  "Plum",
  "Pomegranate",
  "Prune",
  "Raisin",
  "Raspberry",
  "Rambutan",
  "Redcurrant",
  "Salal berry",
  "Satsuma",
  "Star fruit",
  "Strawberry",
  "Tangerine",
  "Tomato",
  "Ugli fruit",
  "Watermelon",
  "Western raspberry (blackcap)",
  "Williams pear or Bartlett pear",
  "Ziziphus mauritiana"
]

export default fruits